[workspace]
resolver = "2"
members = [
    "types42",
    "protocol42",
    "tools",
    "fsw",
]

[profile.dev.package]
protocol42 = { opt-level = 3, debug-assertions = true, overflow-checks = true }
